export const Actions = {
  GET_ORDERS: "GET_ORDERS",
  APPEND_ORDERS: "APPEND_ORDERS",
  UPDATE_ORDER_STATUS: "UPDATE_ORDER_STATUS",
  CANCEL_ORDER: "CANCEL_ORDER",
  GET_ORDERS_OVERVIEW: "GET_ORDERS_OVERVIEW",
  SET_LOADING: "SET_LOADING",
};
