export const Actions = {
  GET_CATEGORIES: "GET_CATEGORIES",
  APPEND_CATEGORIES: "APPEND_CATEGORIES",
  CREATE_CATEGORY: "CREATE_CATEGORY",
  UPDATE_CATEGORY: "UPDATE_CATEGORY",
  DELETE_CATEGORY: "DELETE_CATEGORY",
  GET_CATEGORY_BY_ID: "GET_CATEGORY_BY_ID",
  SET_LOADING: "SET_LOADING",
};
