export const Actions = {
  GET_ITEMS: "GET_ITEMS",
  GET_ITEMS_ID: "GET_ITEMS_ID",
  GET_ITEMS_CREATE: "GET_ITEMS_CREATE",
  GET_ITEMS_UPDATE: "GET_ITEMS_UPDATE",
  GET_ITEM_DELETE: "GET_ITEM_DELETE",
};
