export const Actions = {
  GET_PRICE: "GET_PRICE",
  GET_PRICES: "GET_PRICES",
  CREATE_PRICE: "CREATE_PRICE",
  UPDATE_PRICE: "UPDATE_PRICE",
  DELETE_PRICE: "DELETE_PRICE",
  SET_LOADING: "SET_LOADING",
  SET_ERROR: "SET_ERROR",
};
