export const Actions = {
  GET_QUERIES: "GET_QUERIES",
  APPEND_QUERIES: "APPEND_QUERIES",
  UPDATE_QUERY: "UPDATE_QUERY",
  BULK_UPDATE_QUERIES: "BULK_UPDATE_QUERIES",
  GET_QUERY_STATS: "GET_QUERY_STATS",
  SET_LOADING: "SET_LOADING",
};
